baseURL = "www.edgility.school"
languageCode = "en-us"
title = "EDgility for School"
# themesDir = "../.."
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "EDgility for Schools"

  [params.homepage_meta_tags]
    meta_description = "Engaged, etc Eductation"
    meta_og_title = "Educational Agility for Schools"
    meta_og_type = "website"
    meta_og_url = "https://edgility.school"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ZebMagnuson"
    meta_twitter_creator = "@ZebMagnuson"

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.main]]
    name = "EDgility"
    url = "/edgility_v1_0_0/"
      weight = 10

  [[menu.main]]
      name = "Authors"
      url = "/team/"
      weight = 20

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
